apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team01
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: "Project for team01 apps"
  sourceRepos:
    - '*'       # or '*' if you want
  destinations:
    - namespace: 'team01'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
