apiVersion: v1
kind: Namespace
metadata:
  name: team00
  #labels:
  #  istio-injection: enabled
  annotations:
    sidecar.istio.io/proxyCPU: "100m"
    sidecar.istio.io/proxyCPULimit: "200m"
    sidecar.istio.io/proxyMemory: "128Mi"
    sidecar.istio.io/proxyMemoryLimit: "256Mi"
    sidecar.istio.io/initCPU: "100m"
    sidecar.istio.io/initCPULimit: "100m"
    sidecar.istio.io/initMemory: "64Mi"
    sidecar.istio.io/initMemoryLimit: "128Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-default
  namespace: team00
spec:
  hard:
    requests.cpu: "10"
    limits.cpu: "10"
    requests.memory: 8Gi
    limits.memory: 8Gi
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-default
  namespace: team00
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      max:
        cpu: "2"
        memory: "2Gi"
