apiVersion: v1
kind: Namespace
metadata:
  name: team00
  labels:
    istio.io/rev: 1-20-4
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-default
  namespace: team00
spec:
  hard:
    requests.cpu: "10"
    limits.cpu: "10"
    requests.memory: 8Gi
    limits.memory: 8Gi
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-default
  namespace: team00
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      max:
        cpu: "2"
        memory: "2Gi"
